###############################################
#                    Pages                    #
###############################################

lobby:
    path: /
    methods:
        - GET
    defaults:
        _controller: web-interface.page-controller:lobbyAction

profile:
    path: /profile
    methods:
        - GET
    defaults:
        _controller: web-interface.page-controller:profileAction

game:
    path: /game/{id}
    methods:
        - GET
    defaults:
        _controller: web-interface.page-controller:gameAction

###############################################
#                Chat Service                 #
###############################################

write_message:
    path: /api/chat/chats/{chatId}/write-message
    methods:
        - POST
    defaults:
        _controller: web-interface.chat-controller:writeMessageAction
        _format: json

messages:
    path: /api/chat/chats/{chatId}/messages
    methods:
        - GET
    defaults:
        _controller: web-interface.chat-controller:messagesAction
        _format: json

###############################################
#             Connect Four Service            #
###############################################

open:
    path: /api/connect-four/games/open
    methods:
        - POST
    defaults:
        _controller: web-interface.connect-four-controller:openAction
        _format: json

abort:
    path: /api/connect-four/games/{gameId}/abort
    methods:
        - POST
    defaults:
        _controller: web-interface.connect-four-controller:abortAction
        _format: json

join:
    path: /api/connect-four/games/{gameId}/join
    methods:
        - POST
    defaults:
        _controller: web-interface.connect-four-controller:joinAction
        _format: json

move:
    path: /api/connect-four/games/{gameId}/move
    methods:
        - POST
    defaults:
        _controller: web-interface.connect-four-controller:moveAction
        _format: json

game_json:
    path: /api/connect-four/games/{gameId}
    methods:
        - GET
    defaults:
        _controller: web-interface.connect-four-controller:showAction
        _format: json

###############################################
#                User Service                 #
###############################################

sign_up:
    path: /api/users/sign-up
    methods:
        - POST
    defaults:
        _controller: web-interface.user-controller:signUpAction
        _format: json
