imports:
    - { resource: services/command_bus.yml }
    - { resource: services/console.yml }
    - { resource: services/game.yml }
    - { resource: services/persistence.yml }
    - { resource: services/query_bus.yml }
    - { resource: services/subscriber.yml }

doctrine:
    dbal:
        connections:
            connect-four:
                url: '%env(GAMBLING_CONNECT_FOUR_DOCTRINE_DBAL_URL)%'
                server_version: 8.0
                charset: utf8mb4
                default_table_options:
                     charset: utf8mb4
                     collate: utf8mb4_unicode_ci
