imports: [{ resource: services/ }]

framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/TicTacToe/Port/Adapter/Translation'

gaming_platform_bus:
    buses:
        tic_tac_toe_command: ~
        tic_tac_toe_query: ~

twig:
    paths: { '%kernel.project_dir%/src/TicTacToe/Port/Adapter/Http/View': tic-tac-toe }

doctrine:
    dbal:
        connections:
            tic-tac-toe:
                url: '%env(resolve:APP_TIC_TAC_TOE_DOCTRINE_DBAL_URL)%'
                server_version: '8.2'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
